class WebSocket:
    def __init__(self):
        ...

    async def read(self, size: int = -1):
        ...

    async def write(self, data: bytes):
        ...

    def ping(self, payload: bytes = b""):
        ...

    def close(self, code: int = 1000, reason: str = ""):
        ...
